AppName: "Country.Love.Api"
EnableOAuthValidation: "true"
ACCESS_RESTRICT: "external"

TimeZoneOffSet: "8"

#redis
#Spring.Data.RedisHost: "127.0.0.1"
#Spring.Data.RedisPort: 6379
#Spring.Data.RedisDatabase: 1
#Spring.Data.RedisTimeOut: 60000

#swagger
SwaggerEnable: true
springfox.documentation.swagger.v2.path: /api-docs

spring.jpa.properties.hibernate.hbm2ddl.auto: update
spring:
  datasource:
         url: "jdbc:mysql://47.98.36.138:3306/test"
         driver-class-name: "com.mysql.jdbc.Driver"
         username : "root"
         password : "123456"
  jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql : true
      show_sql : true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      hbm2ddl: