AppName: "Country.Love.Api"
EnableOAuthValidation: "true"
ACCESS_RESTRICT: "external"

TimeZoneOffSet: "8"

#redis
Spring.Data.RedisHost: "127.0.0.1"
Spring.Data.RedisPort: 6379
Spring.Data.RedisDatabase: 1
Spring.Data.RedisTimeOut: 60000

#swagger
SwaggerEnable: true
springfox.documentation.swagger.v2.path: /api-docs

spring.jpa.properties.hibernate.hbm2ddl.auto: update
spring:
  datasource:
         url: "jdbc:mysql://192.168.1.228:3306/db_test"
         driver-class-name: "com.mysql.jdbc.Driver"
         username : "root"
         password : "root123"
  jpa:
      show-sql : true
      show_sql : true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      hbm2ddl: